spring:
  appconfig:
    otp: auth0
    # otp: twilio
  threads:
    virtual:
      enabled: true
# spring.security.user.name=pankaj
  security:
    user:
      name: pankaj
      password: password
  cloud:
    gateway.mvc:
      routesMap:
        product-service:
          uri: http://localhost:30001
          predicates:
            - Path=/api/products/**
          filters:
            - name: AddRequestHeader
              args:
                name: X-Test
                values: product-service
        order-service:
          uri: http://localhost:30003
          predicates:
            - Path=/api/orders/**
            - Method=GET,POST
        inventory-service:
          uri: http://localhost:30002
          predicates:
            - Path=/api/inventories/**
          filters:
            - name: AddRequestHeader
              args:
                name: X-Test
                values: inventory-service
        registry-server:
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - RewritePath=/eureka/web/?(?<segment>.*), /$\{segment}
        registry-server-static:
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        user-service:
          uri: http://localhost:30004
          predicates:
            - Path=/api/users/**
            - Method=GET,POST
        payment-service:
          uri: http://localhost:30005
          predicates:
            - Path=/api/payments/**
            - Method=GET,POST,PATCH
    function.definition: consumeHello
    stream.bindings.consumeHello-in-0.destination: hello-out-0
# logging:
#   level:
#     org.springframework.cloud.gateway.server.mvc: TRACE
#     org.springframework.web: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'