package com.ecom.orderservice.model;

public enum OrderPaymentStatus {
    ORDER_PAYMENT_STATUS_PENDING,
    ORDER_PAYMENT_STATUS_INITIATED,
    ORDER_PAYMENT_STATUS_COMPLETED,
    ORDER_PAYMENT_STATUS_FAILED,
    ORDER_PAYMENT_STATUS_REFUND_INITIATED,
    ORDER_PAYMENT_STATUS_REFUNDED
}
